[package]
name = "graph"
version = "0.1.0"
authors = ["Frederik De Bleser <frederik@debleser.be>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.90", features = ["derive"] }
serde_json = "1.0.39"
